# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=20)),
                ('phone_no', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('fav_subject', models.CharField(max_length=15)),
                ('weak_subject', models.CharField(max_length=15)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrance.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Examiner',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
