# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_auto_20160717_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_no',
        ),
    ]
