# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0004_student_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('exam_id', models.IntegerField()),
                ('weak_subject', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Helpsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weblink', models.URLField()),
                ('pdflink', models.URLField()),
                ('booklink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('exam_id', models.IntegerField()),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_physics', models.IntegerField()),
                ('s_math', models.IntegerField()),
                ('s_chemistry', models.IntegerField()),
                ('s_english', models.IntegerField()),
                ('s_aptitude', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='score',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrance.Student'),
        ),
        migrations.AddField(
            model_name='database',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrance.Question'),
        ),
        migrations.AddField(
            model_name='database',
            name='Student_Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrance.Student_Profile'),
        ),
    ]
