# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0005_auto_20160717_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Profile',
            new_name='Students_Profile',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='Student_Profile',
            new_name='Students_Profile',
        ),
    ]
