# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0006_auto_20160717_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question_ans', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Chemistry_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question_ans', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='English_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question_ans', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Math_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question_ans', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Physics_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question_ans', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Students_Profile',
            new_name='Student_Profile',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='Students_Profile',
            new_name='Student_Profile',
        ),
    ]
