# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0007_auto_20160717_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aptitude_Question',
        ),
        migrations.DeleteModel(
            name='Chemistry_Question',
        ),
        migrations.DeleteModel(
            name='English_Question',
        ),
        migrations.DeleteModel(
            name='Math_Question',
        ),
        migrations.DeleteModel(
            name='Physics_Question',
        ),
    ]
