# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0008_auto_20160717_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question', models.CharField(max_length=500)),
                ('s_question_ans', models.CharField(max_length=50)),
                ('l_question_ans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chemistry_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question', models.CharField(max_length=500)),
                ('s_question_ans', models.CharField(max_length=50)),
                ('l_question_ans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='English_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question', models.CharField(max_length=500)),
                ('s_question_ans', models.CharField(max_length=50)),
                ('l_question_ans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Math_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question', models.CharField(max_length=500)),
                ('s_question_ans', models.CharField(max_length=50)),
                ('l_question_ans', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Physics_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_question', models.CharField(max_length=500)),
                ('l_question', models.CharField(max_length=500)),
                ('s_question_ans', models.CharField(max_length=50)),
                ('l_question_ans', models.CharField(max_length=50)),
            ],
        ),
    ]
