# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0009_aptitude_question_chemistry_question_english_question_math_question_physics_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_option', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='database',
            name='Question',
        ),
        migrations.RemoveField(
            model_name='database',
            name='Student_Profile',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='Student',
        ),
        migrations.RenameField(
            model_name='physics_question',
            old_name='l_question',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='physics_question',
            name='l_question_ans',
        ),
        migrations.RemoveField(
            model_name='physics_question',
            name='s_question',
        ),
        migrations.RemoveField(
            model_name='physics_question',
            name='s_question_ans',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_no',
        ),
        migrations.DeleteModel(
            name='Database',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
