# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0010_auto_20160727_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aptitude_question',
            old_name='l_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='chemistry_question',
            old_name='l_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='english_question',
            old_name='l_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='math_question',
            old_name='l_question',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='aptitude_question',
            name='l_question_ans',
        ),
        migrations.RemoveField(
            model_name='aptitude_question',
            name='s_question',
        ),
        migrations.RemoveField(
            model_name='aptitude_question',
            name='s_question_ans',
        ),
        migrations.RemoveField(
            model_name='chemistry_question',
            name='l_question_ans',
        ),
        migrations.RemoveField(
            model_name='chemistry_question',
            name='s_question',
        ),
        migrations.RemoveField(
            model_name='chemistry_question',
            name='s_question_ans',
        ),
        migrations.RemoveField(
            model_name='english_question',
            name='l_question_ans',
        ),
        migrations.RemoveField(
            model_name='english_question',
            name='s_question',
        ),
        migrations.RemoveField(
            model_name='english_question',
            name='s_question_ans',
        ),
        migrations.RemoveField(
            model_name='math_question',
            name='l_question_ans',
        ),
        migrations.RemoveField(
            model_name='math_question',
            name='s_question',
        ),
        migrations.RemoveField(
            model_name='math_question',
            name='s_question_ans',
        ),
        migrations.AddField(
            model_name='rightans',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
