# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0012_physics_question_option_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitude_question',
            name='option_a',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='aptitude_question',
            name='option_b',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='aptitude_question',
            name='option_c',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='aptitude_question',
            name='option_d',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='chemistry_question',
            name='option_a',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='chemistry_question',
            name='option_b',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='chemistry_question',
            name='option_c',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='chemistry_question',
            name='option_d',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='english_question',
            name='option_a',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='english_question',
            name='option_b',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='english_question',
            name='option_c',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='english_question',
            name='option_d',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='math_question',
            name='option_a',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='math_question',
            name='option_b',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='math_question',
            name='option_c',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='math_question',
            name='option_d',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='physics_question',
            name='option_b',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='physics_question',
            name='option_c',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='physics_question',
            name='option_d',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
