# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0013_auto_20160727_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favorite_subject',
            field=models.CharField(default='Maths', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='username', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='weak_subject',
            field=models.CharField(default='Physics', max_length=20),
        ),
    ]
