# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0014_auto_20160727_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitude_question',
            name='correct_option',
            field=models.CharField(default='c', max_length=50),
        ),
        migrations.AddField(
            model_name='chemistry_question',
            name='correct_option',
            field=models.CharField(default='c', max_length=50),
        ),
        migrations.AddField(
            model_name='english_question',
            name='correct_option',
            field=models.CharField(default='c', max_length=50),
        ),
        migrations.AddField(
            model_name='math_question',
            name='correct_option',
            field=models.CharField(default='c', max_length=50),
        ),
        migrations.AddField(
            model_name='physics_question',
            name='correct_option',
            field=models.CharField(default='c', max_length=50),
        ),
    ]
